### ISSUE TITLE
This does not output correct JSON format

### ISSUE THREAD

**Issue by ericagredo** [ivbeg/newsworker#1]
The output is not correct JSON because all the dictionaries are in single quotes and not "" (double quotes)

**Comment by ivbeg** [comment]
@ericagredo this is correct output format as python dict. If you need JSON, just use 
```
import json

//some code here

json.dumps(feed)

```

**Comment by kernc** [comment]
> this is correct output format as python dict. If you need JSON, just use
> 
> ```
> import json
> 
> //some code here
> 
> json.dumps(feed)
> ```

Does this mean one first needed to conveniently `eval(open(file).read())`? Compared to parsing JSON, this is unsafe.
